name: Run pytest tests on Ubuntu and Windows

on:
  push:
    branches:
      - '*'  # This will trigger the workflow on every branch push, including main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements_tests.txt 
      working-directory: ./

    - name: Run pytest
      run: |
        pytest  # Replace with your pytest command
      working-directory: ./tests/